language: python

python:
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"

install:
    - python3 setup.py install

cache: pip

script: "pytest"

after_script:
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh)"


notifications:
    email: false
